PEH_LARAVEL_ROOT="${PEH_LARAVEL_ROOT:-/app/www}"

# Generate Laravel .env file using docker/kubernetes secrets
ENVFILE="$PEH_LARAVEL_ROOT/.env"
BASEENVFILE="$ENVFILE.base"

echo -e "\n# This file was autogenerated by entrypoint.sh, do not edit\n# From .env.base:\n" > $ENVFILE
cat $BASEENVFILE >> $ENVFILE
echo -e "\n# From orchestrator secrets:\n" >> $ENVFILE

# https://stackoverflow.com/a/5247919
# won't work with spaces and odd characters.  no stupid secret names!
# catch '..' to remove duplicative kubernetes secrets
if [ -d /etc/secret ]; then
	for F in $( find /etc/secret -name 'LARAVEL_*' | grep -v '\.\.' )
	do
		BASENAME="$( basename "$F" )"
		# https://stackoverflow.com/a/10771857
		# https://stackoverflow.com/a/428580
		echo "${BASENAME:8}=$( <$F )" >> $ENVFILE
	done
fi
